"""Initial schema

Revision ID: eda2eb725600
Revises: 
Create Date: 2026-09-05 22:51:53.973218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda2eb725600'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('placement_periods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('data_validation_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingestion_job_id', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_period_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('special_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['placement_period_id'], ['placement_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=True),
    sa.Column('placement_period_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['placement_period_id'], ['placement_periods.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_period_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['placement_period_id'], ['placement_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('placed_count', sa.Integer(), nullable=False),
    sa.Column('empty_quota', sa.Integer(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_table('position_qualifications',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('position_id', 'qualification_id')
    )
    op.create_table('raw_extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_extractions')
    op.drop_table('position_qualifications')
    op.drop_table('placement_scores')
    op.drop_table('source_documents')
    op.drop_table('qualification_versions')
    op.drop_table('positions')
    op.drop_table('data_validation_logs')
    op.drop_table('qualifications')
    op.drop_table('placement_periods')
    op.drop_table('institutions')
    op.drop_table('ingestion_jobs')
    op.drop_table('cities')
    # ### end Alembic commands ###
